### ISSUE TITLE
Citation file?

### ISSUE THREAD

**Issue by hattom** [AndiH/gpu-lang-compat#1]
I just spotted on the website that you have a DOI for this chart. Do you want to add a citation file [1] for the repository as well for those who might not otherwise have spotted it?

I think GitHub does a sensible thing for repositories with a `CITATION.cff` file present.

[1] e.g. https://citation-file-format.github.io/

**Comment by AndiH** [comment]
A very good idea! I'll try to add one ASAP. Thanks!
